local inspect = require("devtools.inspect")
local describe = require('devtools.tests.define.describe')
local host = require("devtools.host")

describe("lookup host", function()
    it("get_lua_host detects nvim", function()
        -- can only detect neovim when running in tests, still useful to detect this works!
        local result = host.get_lua_vm_host()
        assert.are.equal("nvim", result)
    end)
    it("call get_lua_host repeatedly to verify cache works", function()
        local result = host.get_lua_vm_host()
        result = host.get_lua_vm_host()
        assert.are.equal("nvim", result)
    end)
    it("is_nvim returns true", function()
        assert.is_true(host.is_nvim())
    end)
    it("is_hammerspoon returns false", function()
        assert.is_false(host.is_hammerspoon())
    end)
end)
